<a href="https://colab.research.google.com/github/Rony-San/COMPETENCIA-AI4ENG-UDEA---Semestre-2024-2/blob/main/04%20-%20an%C3%A1lisis%20mejor%20modelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:

!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

replicating local resources

In [3]:
import pandas as pd

# Importación de datos

In [4]:
!pip install gdown

import gdown

# Descargar el archivo CSV desde Google Drive
file_url = "https://drive.google.com/uc?export=download&id=1itG_BI2510E75FDEY2l7xf7nV3RZqgC_"
output = "data.csv"
gdown.download(file_url, output, quiet=False)

Requirement already satisfied: gdown in /usr/local/lib/python3.10/dist-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from gdown) (4.12.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from gdown) (3.16.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from gdown) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from gdown) (4.66.6)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->gdown) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (2024.8.30)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->gdown) (1.7.1)

Downloading...
From (original): https://drive.google.com/uc?export=download&id=1itG_BI2510E75FDEY2l7xf7nV3RZqgC_
From (redirected): https://drive.google.com/uc?export=download&id=1itG_BI2510E75FDEY2l7xf7nV3RZqgC_&confirm=t&uuid=0965e79d-81e0-4f54-bed5-3141768b428d
To: /content/data.csv
100%|██████████| 118M/118M [00:01<00:00, 92.6MB/s]

'data.csv'

In [5]:
import pandas as pd

# Cargar el archivo CSV en un DataFrame
df = pd.read_csv("data.csv")

df.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO,RENDIMIENTO_GLOBAL
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Postgrado,No,medio-alto
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Técnica o tecnológica incompleta,No,bajo
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,No,bajo
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Secundaria (Bachillerato) completa,No,alto
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Primaria completa,No,medio-bajo

In [6]:
# Mostrar información general del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 692500 entries, 0 to 692499
Data columns (total 12 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   ID                              692500 non-null  int64
 1   PERIODO                         692500 non-null  int64
 2   ESTU_PRGM_ACADEMICO             692500 non-null  object
 3   ESTU_PRGM_DEPARTAMENTO          692500 non-null  object
 4   ESTU_VALORMATRICULAUNIVERSIDAD  686213 non-null  object
 5   ESTU_HORASSEMANATRABAJA         661643 non-null  object
 6   FAMI_ESTRATOVIVIENDA            660363 non-null  object
 7   FAMI_TIENEINTERNET              665871 non-null  object
 8   FAMI_EDUCACIONPADRE             669322 non-null  object
 9   FAMI_EDUCACIONMADRE             668836 non-null  object
 10  ESTU_PAGOMATRICULAPROPIO        686002 non-null  object
 11  RENDIMIENTO_GLOBAL              692500 non-null  object
dtypes: int64(2), object(10)
memory usage: 63.4+ MB

In [7]:
# Contar la cantidad de estudiantes por programa académico
df['ESTU_PRGM_ACADEMICO'].value_counts()

ESTU_PRGM_ACADEMICO
DERECHO                                                   53244
ADMINISTRACION DE EMPRESAS                                51902
CONTADURIA PUBLICA                                        39664
PSICOLOGIA                                                31932
INGENIERIA INDUSTRIAL                                     28481
                                                          ...
LICENCIATURA EN ESPAÑOL Y FILOLOGÍA                           1
ADMINISTRACION EN NEGOCIOS INTERNACIONALES                    1
ADMINISTRACION DE COMERCIO EXTERIOR                           1
LICENCIATURA EN EDUCACI¿N F¿SICA RECREACI¿N Y DEPORTES        1
PROFESIONAL EN INVESTIGACIÓN CRIMINAL                         1
Name: count, Length: 948, dtype: int64

# Manejo de Datos faltantes

In [8]:
# Verificar qué columnas tienen valores faltantes y cuántos son
missing_values = df.isnull().sum()

# Mostrar solo las columnas que tienen valores faltantes
missing_values = missing_values[missing_values > 0]

# Mostrar el resultado
print(missing_values)

ESTU_VALORMATRICULAUNIVERSIDAD     6287
ESTU_HORASSEMANATRABAJA           30857
FAMI_ESTRATOVIVIENDA              32137
FAMI_TIENEINTERNET                26629
FAMI_EDUCACIONPADRE               23178
FAMI_EDUCACIONMADRE               23664
ESTU_PAGOMATRICULAPROPIO           6498
dtype: int64

In [9]:
# Rellenar valores faltantes con la moda o con un valor específico según el contexto
df['ESTU_VALORMATRICULAUNIVERSIDAD'].fillna(df['ESTU_VALORMATRICULAUNIVERSIDAD'].mode()[0], inplace=True)
df['ESTU_HORASSEMANATRABAJA'].fillna("Desconocido", inplace=True)  # O puedes usar "0" si aplica
df['FAMI_ESTRATOVIVIENDA'].fillna(df['FAMI_ESTRATOVIVIENDA'].mode()[0], inplace=True)
df['FAMI_TIENEINTERNET'].fillna("Desconocido", inplace=True)  # O puedes usar "No"
df['FAMI_EDUCACIONPADRE'].fillna("No sabe", inplace=True)
df['FAMI_EDUCACIONMADRE'].fillna("No sabe", inplace=True)
df['ESTU_PAGOMATRICULAPROPIO'].fillna(df['ESTU_PAGOMATRICULAPROPIO'].mode()[0], inplace=True)

<ipython-input-9-e064defbbe53>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ESTU_VALORMATRICULAUNIVERSIDAD'].fillna(df['ESTU_VALORMATRICULAUNIVERSIDAD'].mode()[0], inplace=True)
<ipython-input-9-e064defbbe53>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ESTU_HORASSEMANATRABAJA'].fillna("Desconocido", inplace=True)  # O puedes usar "0" si aplica
<ipython-input-9-e064defbbe53>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FAMI_ESTRATOVIVIENDA'].fillna(df['FAMI_ESTRATOVIVIENDA'].mode()[0], inplace=True)
<ipython-input-9-e064defbbe53>:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FAMI_TIENEINTERNET'].fillna("Desconocido", inplace=True)  # O puedes usar "No"
<ipython-input-9-e064defbbe53>:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FAMI_EDUCACIONPADRE'].fillna("No sabe", inplace=True)
<ipython-input-9-e064defbbe53>:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['FAMI_EDUCACIONMADRE'].fillna("No sabe", inplace=True)
<ipython-input-9-e064defbbe53>:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ESTU_PAGOMATRICULAPROPIO'].fillna(df['ESTU_PAGOMATRICULAPROPIO'].mode()[0], inplace=True)

In [10]:
# Verificar qué columnas tienen valores faltantes y cuántos son
missing_values = df.isnull().sum()

missing_values = missing_values[missing_values > 0]

print(missing_values)

Series([], dtype: int64)

In [11]:
# Listar todas las columnas categóricas (en este caso, todas las columnas del DataFrame)
categorical_columns = df.columns

# Revisar la frecuencia de valores en cada columna categórica
for column in categorical_columns:
    print(f"Frecuencia de valores en {column}:")
    print(df[column].value_counts())
    print("\n")

Frecuencia de valores en ID:
ID
904256    1
915348    1
373660    1
691058    1
790510    1
         ..
190471    1
882806    1
297614    1
540154    1
933374    1
Name: count, Length: 692500, dtype: int64


Frecuencia de valores en PERIODO:
PERIODO
20195    180873
20203    171838
20212    171412
20183    164818
20194      1472
20213      1178
20202       490
20184       254
20196       165
Name: count, dtype: int64


Frecuencia de valores en ESTU_PRGM_ACADEMICO:
ESTU_PRGM_ACADEMICO
DERECHO                                                   53244
ADMINISTRACION DE EMPRESAS                                51902
CONTADURIA PUBLICA                                        39664
PSICOLOGIA                                                31932
INGENIERIA INDUSTRIAL                                     28481
                                                          ...
LICENCIATURA EN ESPAÑOL Y FILOLOGÍA                           1
ADMINISTRACION EN NEGOCIOS INTERNACIONALES                    1
ADMINISTRACION DE COMERCIO EXTERIOR                           1
LICENCIATURA EN EDUCACI¿N F¿SICA RECREACI¿N Y DEPORTES        1
PROFESIONAL EN INVESTIGACIÓN CRIMINAL                         1
Name: count, Length: 948, dtype: int64


Frecuencia de valores en ESTU_PRGM_DEPARTAMENTO:
ESTU_PRGM_DEPARTAMENTO
BOGOTÁ             282159
ANTIOQUIA           83607
VALLE               44588
ATLANTICO           41020
SANTANDER           28828
NORTE SANTANDER     22588
BOLIVAR             20629
BOYACA              14048
CUNDINAMARCA        14018
NARIÑO              13454
RISARALDA           12679
CORDOBA             12188
TOLIMA              11921
CALDAS              11640
CAUCA               11471
HUILA                9995
MAGDALENA            9512
SUCRE                8674
CESAR                8279
QUINDIO              8229
META                 7910
LA GUAJIRA           4778
CHOCO                4289
CAQUETA              2659
CASANARE             1852
PUTUMAYO              795
ARAUCA                589
AMAZONAS               40
GUAVIARE               37
VAUPES                 14
SAN ANDRES             10
Name: count, dtype: int64


Frecuencia de valores en ESTU_VALORMATRICULAUNIVERSIDAD:
ESTU_VALORMATRICULAUNIVERSIDAD
Entre 1 millón y menos de 2.5 millones      210335
Entre 2.5 millones y menos de 4 millones    127430
Menos de 500 mil                             80263
Entre 500 mil y menos de 1 millón            78704
Entre 4 millones y menos de 5.5 millones     69736
Más de 7 millones                            68014
Entre 5.5 millones y menos de 7 millones     38490
No pagó matrícula                            19528
Name: count, dtype: int64


Frecuencia de valores en ESTU_HORASSEMANATRABAJA:
ESTU_HORASSEMANATRABAJA
Más de 30 horas        249352
0                      116550
Entre 11 y 20 horas    115857
Entre 21 y 30 horas     92693
Menos de 10 horas       87191
Desconocido             30857
Name: count, dtype: int64


Frecuencia de valores en FAMI_ESTRATOVIVIENDA:
FAMI_ESTRATOVIVIENDA
Estrato 2      264808
Estrato 3      210685
Estrato 1      111991
Estrato 4       65514
Estrato 5       23608
Estrato 6       12605
Sin Estrato      3289
Name: count, dtype: int64


Frecuencia de valores en FAMI_TIENEINTERNET:
FAMI_TIENEINTERNET
Si             592514
No              73357
Desconocido     26629
Name: count, dtype: int64


Frecuencia de valores en FAMI_EDUCACIONPADRE:
FAMI_EDUCACIONPADRE
Secundaria (Bachillerato) completa      128289
Primaria incompleta                     125675
Educación profesional completa           83117
Secundaria (Bachillerato) incompleta     71654
Técnica o tecnológica completa           62995
Primaria completa                        55958
Postgrado                                44169
No sabe                                  39770
Educación profesional incompleta         27084
Técnica o tecnológica incompleta         22552
Ninguno                                  22008
No Aplica                                 9229
Name: count, dtype: int64


Frecuencia de valores en FAMI_EDUCACIONMADRE:
FAMI_EDUCACIONMADRE
Secundaria (Bachillerato) completa      141744
Primaria incompleta                      99420
Técnica o tecnológica completa           89542
Educación profesional completa           85326
Secundaria (Bachillerato) incompleta     81012
Primaria completa                        56125
Postgrado                                46246
Técnica o tecnológica incompleta         27533
No sabe                                  26681
Educación profesional incompleta         22470
Ninguno                                  14483
No Aplica                                 1918
Name: count, dtype: int64


Frecuencia de valores en ESTU_PAGOMATRICULAPROPIO:
ESTU_PAGOMATRICULAPROPIO
No    388699
Si    303801
Name: count, dtype: int64


Frecuencia de valores en RENDIMIENTO_GLOBAL:
RENDIMIENTO_GLOBAL
alto          175619
bajo          172987
medio-bajo    172275
medio-alto    171619
Name: count, dtype: int64

# Encoding

In [12]:
import pandas as pd

"""
Este código realiza el preprocesamiento de un dataset con datos categóricos y ordinales.
1. Se codifican las columnas ordinales, respetando el orden de las categorías definidas. Esto incluye:
   - 'ESTU_VALORMATRICULAUNIVERSIDAD', que refleja rangos de valores de matrícula.
   - 'FAMI_ESTRATOVIVIENDA', que refleja el estrato socioeconómico del hogar.
   - 'ESTU_HORASSEMANATRABAJA', que refleja el número de horas que el estudiante trabaja a la semana.

2. Se aplicará **one-hot encoding** a las columnas nominales, es decir, aquellas que no tienen un orden natural:
   - 'ESTU_PRGM_ACADEMICO', 'ESTU_PRGM_DEPARTAMENTO', 'FAMI_TIENEINTERNET',
     'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE', 'ESTU_PAGOMATRICULAPROPIO', 'RENDIMIENTO_GLOBAL'.

3. Las columnas 'ID' y 'PERIODO' no se codifican ni transforman, ya que son necesarias para el análisis, pero se mantienen en el dataset.

4. Finalmente, los valores booleanos resultantes de `pd.get_dummies()` (utilizado para one-hot encoding) se convierten a enteros (0 y 1) para que puedan ser utilizados en un modelo de machine learning.
"""

# Codificación de columnas ordinales

# Definir el orden para las categorías de 'ESTU_VALORMATRICULAUNIVERSIDAD'
valores_matricula = ['Menos de 500 mil', 'Entre 500 mil y menos de 1 millón',
                     'Entre 1 millón y menos de 2.5 millones', 'Entre 2.5 millones y menos de 4 millones',
                     'Entre 4 millones y menos de 5.5 millones', 'Entre 5.5 millones y menos de 7 millones',
                     'Más de 7 millones', 'No pagó matrícula']
df['ESTU_VALORMATRICULAUNIVERSIDAD'] = pd.Categorical(df['ESTU_VALORMATRICULAUNIVERSIDAD'],
                                                      categories=valores_matricula, ordered=True)
df['ESTU_VALORMATRICULAUNIVERSIDAD'] = df['ESTU_VALORMATRICULAUNIVERSIDAD'].cat.codes

# Definir el orden para 'FAMI_ESTRATOVIVIENDA'
estrato_vivienda = ['Estrato 1', 'Estrato 2', 'Estrato 3', 'Estrato 4', 'Estrato 5', 'Estrato 6', 'Sin Estrato']
df['FAMI_ESTRATOVIVIENDA'] = pd.Categorical(df['FAMI_ESTRATOVIVIENDA'], categories=estrato_vivienda, ordered=True)
df['FAMI_ESTRATOVIVIENDA'] = df['FAMI_ESTRATOVIVIENDA'].cat.codes

# Definir el orden para 'ESTU_HORASSEMANATRABAJA'
horas_trabajo = ['0', 'Menos de 10 horas', 'Entre 11 y 20 horas', 'Entre 21 y 30 horas', 'Más de 30 horas', 'Desconocido']
df['ESTU_HORASSEMANATRABAJA'] = pd.Categorical(df['ESTU_HORASSEMANATRABAJA'], categories=horas_trabajo, ordered=True)
df['ESTU_HORASSEMANATRABAJA'] = df['ESTU_HORASSEMANATRABAJA'].cat.codes

# Lista de columnas nominales para aplicar one-hot encoding (excluyendo las ordinales ya codificadas)
nominal_columns = ['ESTU_PRGM_ACADEMICO', 'ESTU_PRGM_DEPARTAMENTO', 'FAMI_TIENEINTERNET',
                   'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE', 'ESTU_PAGOMATRICULAPROPIO', 'RENDIMIENTO_GLOBAL']

df_encoded = pd.get_dummies(df, columns=nominal_columns)

# Convertir los valores True/False a 0/1
df_encoded = df_encoded.astype(int)

# Verificar los primeros resultados y dimensiones del dataset final
print(df_encoded.head())
print(f"El dataset tiene {df_encoded.shape[0]} filas y {df_encoded.shape[1]} columnas.")

       ID  PERIODO  ESTU_VALORMATRICULAUNIVERSIDAD  ESTU_HORASSEMANATRABAJA  \
0  904256    20212                               5                        1
1  645256    20212                               3                        0
2  308367    20203                               3                        4
3  470353    20195                               4                        0
4  989032    20212                               3                        3

   FAMI_ESTRATOVIVIENDA  \
0                     2
1                     2
2                     2
3                     3
4                     2

   ESTU_PRGM_ACADEMICO_3°  CICLO PROFESIONAL NEGOCIOS INTERNACIONALES  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   ESTU_PRGM_ACADEMICO_ACTIVIDAD FISICA Y DEPORTE  \
0                                               0
1                                               0
2                                               0
3                                               0
4                                               0

   ESTU_PRGM_ACADEMICO_ACUICULTURA  ESTU_PRGM_ACADEMICO_ADMINISTRACION  \
0                                0                                   0
1                                0                                   0
2                                0                                   0
3                                0                                   0
4                                0                                   0

   ESTU_PRGM_ACADEMICO_ADMINISTRACION  FINANCIERA  ...  \
0                                               0  ...
1                                               0  ...
2                                               0  ...
3                                               0  ...
4                                               0  ...

   FAMI_EDUCACIONMADRE_Secundaria (Bachillerato) completa  \
0                                                  0
1                                                  0
2                                                  1
3                                                  1
4                                                  0

   FAMI_EDUCACIONMADRE_Secundaria (Bachillerato) incompleta  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   FAMI_EDUCACIONMADRE_Técnica o tecnológica completa  \
0                                                  0
1                                                  0
2                                                  0
3                                                  0
4                                                  0

   FAMI_EDUCACIONMADRE_Técnica o tecnológica incompleta  \
0                                                  0
1                                                  1
2                                                  0
3                                                  0
4                                                  0

   ESTU_PAGOMATRICULAPROPIO_No  ESTU_PAGOMATRICULAPROPIO_Si  \
0                            1                            0
1                            1                            0
2                            1                            0
3                            1                            0
4                            1                            0

   RENDIMIENTO_GLOBAL_alto  RENDIMIENTO_GLOBAL_bajo  \
0                        0                        0
1                        0                        1
2                        0                        1
3                        1                        0
4                        0                        0

   RENDIMIENTO_GLOBAL_medio-alto  RENDIMIENTO_GLOBAL_medio-bajo
0                              1                              0
1                              0                              0
2                              0                              0
3                              0                              0
4                              0                              1

[5 rows x 1017 columns]
El dataset tiene 692500 filas y 1017 columnas.

In [13]:
# Mostrar las primeras filas del dataset después del one-hot encoding
df_encoded.head()

,ID,PERIODO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,ESTU_PRGM_ACADEMICO_3° CICLO PROFESIONAL NEGOCIOS INTERNACIONALES,ESTU_PRGM_ACADEMICO_ACTIVIDAD FISICA Y DEPORTE,ESTU_PRGM_ACADEMICO_ACUICULTURA,ESTU_PRGM_ACADEMICO_ADMINISTRACION,ESTU_PRGM_ACADEMICO_ADMINISTRACION FINANCIERA,...,FAMI_EDUCACIONMADRE_Secundaria (Bachillerato) completa,FAMI_EDUCACIONMADRE_Secundaria (Bachillerato) incompleta,FAMI_EDUCACIONMADRE_Técnica o tecnológica completa,FAMI_EDUCACIONMADRE_Técnica o tecnológica incompleta,ESTU_PAGOMATRICULAPROPIO_No,ESTU_PAGOMATRICULAPROPIO_Si,RENDIMIENTO_GLOBAL_alto,RENDIMIENTO_GLOBAL_bajo,RENDIMIENTO_GLOBAL_medio-alto,RENDIMIENTO_GLOBAL_medio-bajo
0,904256,20212,5,1,2,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
1,645256,20212,3,0,2,0,0,0,0,0,...,0,0,0,1,1,0,0,1,0,0
2,308367,20203,3,4,2,0,0,0,0,0,...,1,0,0,0,1,0,0,1,0,0
3,470353,20195,4,0,3,0,0,0,0,0,...,1,0,0,0,1,0,1,0,0,0
4,989032,20212,3,3,2,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1

In [14]:
!pip install h2o

Collecting h2o
  Downloading h2o-3.46.0.6.tar.gz (265.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 265.8/265.8 MB 1.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from h2o) (2.32.3)
Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (from h2o) (0.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->h2o) (2024.8.30)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.46.0.6-py2.py3-none-any.whl size=265859786 sha256=2940bf3451a82ab019aceaae6b87fc9eaddcb1b4afb435b2e548321c94098cdc
  Stored in directory: /root/.cache/pip/wheels/0c/95/eb/b449c73f478dbc4557b80170cf7f2aa6db15862877e9a63536
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.46.0.6

In [16]:
import h2o
from h2o.estimators import H2OGradientBoostingEstimator, H2ORandomForestEstimator, H2ODeepLearningEstimator

# Inicializar H2O
h2o.init()

# Convertir 'RENDIMIENTO_GLOBAL' a una sola columna categórica
df['RENDIMIENTO_GLOBAL'] = pd.Categorical(
    df['RENDIMIENTO_GLOBAL'],
    categories=['bajo', 'medio-bajo', 'medio-alto', 'alto'],
    ordered=True
)

# Tomar una muestra del dataset para reducir carga computacional
df_sample = df.sample(frac=0.4, random_state=42)  # Usa el 10% de los datos

# Separar características y etiquetas antes de convertir a H2OFrame
X = df_sample.drop(columns=['RENDIMIENTO_GLOBAL', 'ID', 'PERIODO'])  # Eliminar columnas irrelevantes
y = df_sample['RENDIMIENTO_GLOBAL']

# Convertir a H2OFrame
h2o_df = h2o.H2OFrame(pd.concat([X, y], axis=1))

# Dividir en entrenamiento y prueba
train, test = h2o_df.split_frame(ratios=[0.8], seed=42)

# Configurar características y etiqueta
x_columns = X.columns.tolist()
y_column = 'RENDIMIENTO_GLOBAL'

# Entrenar el modelo GBM
gbm = H2OGradientBoostingEstimator(seed=42)
gbm.train(x=x_columns, y=y_column, training_frame=train)

# Entrenar el modelo Random Forest
rf = H2ORandomForestEstimator(seed=42)
rf.train(x=x_columns, y=y_column, training_frame=train)

# Entrenar el modelo Deep Learning
dl = H2ODeepLearningEstimator(seed=42)
dl.train(x=x_columns, y=y_column, training_frame=train)

# Evaluar cada modelo en el conjunto de prueba
print("Evaluación GBM:")
print(gbm.model_performance(test))

print("\nEvaluación Random Forest:")
print(rf.model_performance(test))

print("\nEvaluación Deep Learning:")
print(dl.model_performance(test))

# Comparar los resultados entre los tres modelos

Checking whether there is an H2O instance running at http://localhost:54321. connected.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         3 mins 13 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.6
H2O_cluster_version_age:    28 days, 15 hours and 32 minutes
H2O_cluster_name:           H2O_from_python_unknownUser_ny22i5
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2.949 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
gbm Model Build progress: |██████████████████████████████████████████████████████| (done) 100%
drf Model Build progress: |██████████████████████████████████████████████████████| (done) 100%
deeplearning Model Build progress: |█████████████████████████████████████████████| (done) 100%
Evaluación GBM:
ModelMetricsMultinomial: gbm
** Reported on test data. **

MSE: 0.46804471217037086
RMSE: 0.6841379335853047
LogLoss: 1.214182534510979
Mean Per-Class Error: 0.5727962026946337
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
alto    bajo    medio-alto    medio-bajo    Error     Rate
------  ------  ------------  ------------  --------  ---------------
8655    1147    2599          1502          0.377472  5,248 / 13,903
1143    7581    1866          3269          0.452991  6,278 / 13,859
3873    2882    3530          3305          0.74025   10,060 / 13,590
2045    5059    2863          3867          0.720471  9,967 / 13,834
15716   16669   10858         11943         0.571757  31,553 / 55,186

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.428243
2    0.710434
3    0.897945
4    1

Evaluación Random Forest:
ModelMetricsMultinomial: drf
** Reported on test data. **

MSE: 0.4661498727659822
RMSE: 0.6827516918807175
LogLoss: 1.3204381898133053
Mean Per-Class Error: 0.5869148006538468
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
alto    bajo    medio-alto    medio-bajo    Error     Rate
------  ------  ------------  ------------  --------  ---------------
8406    1258    2566          1673          0.395382  5,497 / 13,903
1208    7117    1997          3537          0.486471  6,742 / 13,859
3841    2954    3344          3451          0.753937  10,246 / 13,590
2091    4924    2833          3986          0.711869  9,848 / 13,834
15546   16253   10740         12647         0.585891  32,333 / 55,186

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.414109
2    0.691153
3    0.887181
4    1

Evaluación Deep Learning:
ModelMetricsMultinomial: deeplearning
** Reported on test data. **

MSE: 0.4621746707682316
RMSE: 0.679834296551911
LogLoss: 1.2094613737296773
Mean Per-Class Error: 0.5739978196211635
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
alto    bajo    medio-alto    medio-bajo    Error     Rate
------  ------  ------------  ------------  --------  ---------------
8554    759     2943          1647          0.384737  5,349 / 13,903
1010    6500    2161          4188          0.530991  7,359 / 13,859
3752    2103    3923          3812          0.711332  9,667 / 13,590
1993    3958    3303          4580          0.668932  9,254 / 13,834
15309   13320   12330         14227         0.573134  31,629 / 55,186

Top-4 Hit Ratios:
k    hit_ratio
---  -----------
1    0.426866
2    0.71018
3    0.901044
4    1

In [17]:
import gdown
import pandas as pd

# Descargar el archivo CSV desde Google Drive
file_url = "https://drive.google.com/uc?export=download&id=1faotvNj3ki3OECYyM0r_uixbKECcvU_P"

output = "test.csv"
gdown.download(file_url, output, quiet=False)

Downloading...
From: https://drive.google.com/uc?export=download&id=1faotvNj3ki3OECYyM0r_uixbKECcvU_P
To: /content/test.csv
100%|██████████| 50.1M/50.1M [00:00<00:00, 85.1MB/s]

'test.csv'

In [18]:
# Leer el archivo de prueba
test_df = pd.read_csv("test.csv")

# Mostrar las columnas disponibles en el archivo de prueba
print("Columnas disponibles en el archivo de prueba:")
print(test_df.columns)

Columnas disponibles en el archivo de prueba:
Index(['Unnamed: 0', 'ID', 'PERIODO', 'ESTU_PRGM_ACADEMICO',
       'ESTU_PRGM_DEPARTAMENTO', 'ESTU_VALORMATRICULAUNIVERSIDAD',
       'ESTU_HORASSEMANATRABAJA', 'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEINTERNET',
       'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
       'ESTU_PAGOMATRICULAPROPIO'],
      dtype='object')

In [19]:
import h2o
import pandas as pd

# Inicializar H2O (si no está ya inicializado)
h2o.init()

# Leer el archivo de prueba
test_df = pd.read_csv("test.csv")

# Preprocesamiento del archivo de prueba
# Codificar las columnas ordinales igual que en el conjunto de entrenamiento
test_df['ESTU_VALORMATRICULAUNIVERSIDAD'] = pd.Categorical(
    test_df['ESTU_VALORMATRICULAUNIVERSIDAD'],
    categories=['Menos de 500 mil', 'Entre 500 mil y menos de 1 millón',
                'Entre 1 millón y menos de 2.5 millones', 'Entre 2.5 millones y menos de 4 millones',
                'Entre 4 millones y menos de 5.5 millones', 'Entre 5.5 millones y menos de 7 millones',
                'Más de 7 millones', 'No pagó matrícula'],
    ordered=True
).codes

test_df['FAMI_ESTRATOVIVIENDA'] = pd.Categorical(
    test_df['FAMI_ESTRATOVIVIENDA'],
    categories=['Estrato 1', 'Estrato 2', 'Estrato 3', 'Estrato 4', 'Estrato 5', 'Estrato 6', 'Sin Estrato'],
    ordered=True
).codes

test_df['ESTU_HORASSEMANATRABAJA'] = pd.Categorical(
    test_df['ESTU_HORASSEMANATRABAJA'],
    categories=['0', 'Menos de 10 horas', 'Entre 11 y 20 horas', 'Entre 21 y 30 horas', 'Más de 30 horas', 'Desconocido'],
    ordered=True
).codes

# Eliminar columnas no utilizadas
test_df = test_df.drop(columns=['PERIODO'], errors='ignore')

# Convertir a H2OFrame
h2o_test = h2o.H2OFrame(test_df)

# Hacer predicciones usando el modelo Deep Learning entrenado
predictions = rf.predict(h2o_test)

# Convertir las predicciones a un DataFrame de pandas
predictions_df = predictions.as_data_frame()

# Crear el archivo de salida para Kaggle
output_df = pd.DataFrame({
    'ID': test_df['ID'],  # Mantener la columna ID del archivo original
    'RENDIMIENTO_GLOBAL': predictions_df['predict']  # Usar la columna de predicción
})

# Guardar el archivo en formato CSV
output_file_path = '/content/submission.csv'
output_df.to_csv(output_file_path, index=False)

print(f"Archivo de predicción guardado en: {output_file_path}")

Checking whether there is an H2O instance running at http://localhost:54321. connected.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         19 mins 13 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.6
H2O_cluster_version_age:    28 days, 15 hours and 48 minutes
H2O_cluster_name:           H2O_from_python_unknownUser_ny22i5
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.946 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
drf prediction progress: |███████████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.10/dist-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'ESTU_PRGM_ACADEMICO' has levels not trained on: ["ADMINISTRACION  DE EMPRESAS.", "ADMINISTRACION DE EMPRESAS.", "ADMINISTRACION INFORMATICA", "ADMINISTRACION TECNOLOGICA", "AGROINDUSTRIA", "ARTE DRAMÁTICO", "CIENCIAS DE LA COMPUTACION", "COMUNICACIÖN SOCIAL", "LICENC.EN EDUCACION BASICA PRIMARIA ENF.EN CIENCIAS NATURALESEDUC.AMBIENTAL MATEMA.LENGUA CASTELLANA", "LICENCIATURA EN EDUCACION BASICA CON ENFASIS EN IDIOMAS EXTRANJEROS", "LICENCIATURA EN EDUCACION BASICA ENFASIS EN CIENCIAS SOCIALES", "LICENCIATURA EN EDUCACION ENFASIS EN HUMANIDADES", "LICENCIATURA EN MATEMATICA E INFORMATICA", "LICENCIATURA EN TECNOLOGÍA E INFORMÁTICA", "NEGOCIOS INTERNACIONALES BILINGUE", "QUÍMICA"]
  warnings.warn(w)
/usr/local/lib/python3.10/dist-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'FAMI_TIENEINTERNET' has levels not trained on: ["nan"]
  warnings.warn(w)
/usr/local/lib/python3.10/dist-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'FAMI_EDUCACIONPADRE' has levels not trained on: ["nan"]
  warnings.warn(w)
/usr/local/lib/python3.10/dist-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'FAMI_EDUCACIONMADRE' has levels not trained on: ["nan"]
  warnings.warn(w)
/usr/local/lib/python3.10/dist-packages/h2o/job.py:81: UserWarning: Test/Validation dataset column 'ESTU_PAGOMATRICULAPROPIO' has levels not trained on: ["nan"]
  warnings.warn(w)
/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

Archivo de predicción guardado en: /content/submission.csv